name: Deploy LaLamboBot

on:
  push:
    branches:
      - master  # Деплой срабатывает при пуше в master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/LaLamboBot
            git pull origin master
            docker compose down
            docker compose up --build -d

